### ISSUE TITLE
Cannot set property 'call' of undefined

### ISSUE THREAD

**Issue by iliailia1212** [kotborealis/minvk#1]
I enter in the console:
const MinVK = require('minvk');
const vk = MinVK({
  mode:"token",
 access_token:"My_token"
});
Displays an error:

```
TypeError: Cannot set property 'call' of undefined
    at module.exports.request.call.longPoll.longPollHelper.messageGetAttachments.uploadPrivateImage.call.isChatId (/var/node/node_modules/minvk/lib/vk.js:27:15)
    at repl:1:12
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:212:10)
    at REPLServer.Interface._line (readline.js:551:8)

```

Node.js version - v4.5.0

**Comment by kotborealis** [comment]
There was an error in usage examples, you're supposed to use it with `new` keyword:

```
const vk = new Minvk({
        mode:"access_token",
        access_token:"..."
    });
```

**Comment by kotborealis** [comment]
Oh, as you can notice, there was another error in readme.
You should use `mode:"access_token"` instead of `mode:"token"`
Thanks for feedback!
